import { Construct } from "constructs";
import { Namespace } from "../.gen/providers/kubernetes/namespace/index.js";
import { Deployment } from "../.gen/providers/kubernetes/deployment/index.js";
import { Service } from "../.gen/providers/kubernetes/service/index.js";
import { Secret } from "../.gen/providers/kubernetes/secret/index.js";
import { PersistentVolumeClaim } from "../.gen/providers/kubernetes/persistent-volume-claim/index.js";
import { type VpnConfig, VpnService } from "../lib/vpn-service.js";
import { createAppIngress } from "../lib/app-ingress.js";
import { createAppProbe } from "../lib/app-probe.js";

/**
 * One construct for every app that is only a Deployment, a Service and a disk.
 *
 * ── WHY THIS EXISTS ──
 * There are fifteen `-native` constructs totalling 3,038 lines and they build the same five
 * resources. `minio-native.ts` and `qdrant-native.ts` are both exactly 158 lines and identical in
 * structure — copy-paste with the values changed. So adding MongoDB meant writing TypeScript,
 * shipping the platform, and restarting it, for a record that says `mongo:7` and a port number.
 *
 * The backend renders a spec into resource configuration and passes it here as JSON. This
 * instantiates it and nothing else — no decisions, no defaults, no per-app branches. Everything
 * that could be got wrong was decided in `renderApp`, where it is unit-tested against the
 * hand-written construct field by field.
 *
 * ── WHY JSON ACROSS THE BOUNDARY ──
 * `APP_SETTINGS_JSON` already does this for game servers, whose comment says it plainly: one blob,
 * so adding a setting needs no change here at all. The same reasoning applies more strongly to a
 * whole app — and cdktf-infra is a separate workspace, so a shared type would be a build-order
 * dependency for no gain. The shape below is a CONTRACT with the renderer, not a duplicate of it:
 * it is what crosses a process boundary, and writing it out is what makes that boundary visible.
 *
 * ── WHAT THIS IS NOT FOR ──
 * Apps with genuine logic keep their constructs. Odoo is 206 lines because it runs a database
 * alongside itself and waits for it; Nextcloud is 215 for similar reasons. Nothing here should grow
 * to accommodate them — the moment this file starts branching on app type, it has become the
 * fifteen files it replaced.
 */

/** What the renderer produces. Kept in sync by the test that renders minio and diffs it. */
export interface RenderedAppConfig {
  namespace: { metadata: { name: string } };
  secret?: { metadata: { name: string; namespace: string }; data: Record<string, string>; type: string };
  pvcs: { metadata: { name: string; namespace: string }; spec: unknown; waitUntilBound: boolean }[];
  deployment: Record<string, any>;
  service: Record<string, any>;
  /** Which port a browser should reach, when the app has a UI worth exposing. */
  ingressPort?: number;
  /** Where a probe should look, so a deployed spec reports health like every other app. */
  health?: { port: number; path: string };
}

export interface SpecAppConfig extends VpnConfig {
  readonly rendered: RenderedAppConfig;
}

export class SpecApp extends Construct {
  constructor(scope: Construct, id: string, config: SpecAppConfig) {
    super(scope, id);
    const { rendered } = config;

    const ns = new Namespace(this, "ns", { metadata: rendered.namespace.metadata });
    const namespaceName = rendered.namespace.metadata.name;

    if (rendered.secret) {
      new Secret(this, "secret", {
        metadata: { ...rendered.secret.metadata, namespace: ns.metadata.name },
        // Plaintext: the provider base64-encodes `data` itself. The values were generated by the
        // backend and are never present in the spec that produced them.
        data: rendered.secret.data,
        type: rendered.secret.type,
      });
    }

    /**
     * Indexed rather than named, because a spec may declare several volumes and CDKTF ids must be
     * unique within a scope. The PVC's own name comes from the renderer, which is what the pod spec
     * already refers to.
     */
    rendered.pvcs.forEach((pvc, i) => {
      new PersistentVolumeClaim(this, `pvc-${i}`, {
        metadata: { ...pvc.metadata, namespace: ns.metadata.name },
        spec: pvc.spec as any,
        waitUntilBound: pvc.waitUntilBound,
      });
    });

    /**
     * The VPN sidecar mutates the pod spec in place, exactly as every hand-written construct does.
     * Applied here rather than in the renderer because it is a cluster concern that needs this
     * scope — and because the renderer is pure, which is what makes it testable.
     */
    const podSpec = rendered.deployment.spec.template.spec;
    VpnService.apply(this, ns.metadata.name, podSpec, config);

    new Deployment(this, "deployment", {
      ...rendered.deployment,
      metadata: { ...rendered.deployment.metadata, namespace: ns.metadata.name },
    } as any);

    new Service(this, "service", {
      ...rendered.service,
      metadata: { ...rendered.service.metadata, namespace: ns.metadata.name },
    } as any);

    // Only when the app has something a person would open. A database has no console, and an
    // ingress pointing at one would be a hostname that answers with a protocol error.
    if (rendered.ingressPort) {
      createAppIngress(this, "ingress", {
        namespace: namespaceName,
        serviceName: rendered.service.metadata.name,
        servicePort: rendered.ingressPort,
        hostname: `${namespaceName}.apps.local`,
      });
    }

    if (rendered.health) {
      createAppProbe(this, "probe", {
        namespace: namespaceName,
        serviceName: rendered.service.metadata.name,
        servicePort: rendered.health.port,
        path: rendered.health.path,
      });
    }
  }
}
