import { Construct } from "constructs";
import { Namespace } from "../.gen/providers/kubernetes/namespace/index.js";
import { Deployment } from "../.gen/providers/kubernetes/deployment/index.js";
import { Service } from "../.gen/providers/kubernetes/service/index.js";
import { Secret } from "../.gen/providers/kubernetes/secret/index.js";
import { PersistentVolumeClaim } from "../.gen/providers/kubernetes/persistent-volume-claim/index.js";
import { VpnService } from "../lib/vpn-service.js";
import { createAppIngress } from "../lib/app-ingress.js";
import { createAppProbe } from "../lib/app-probe.js";
export class SpecApp extends Construct {
    constructor(scope, id, config) {
        super(scope, id);
        const { rendered } = config;
        const ns = new Namespace(this, "ns", { metadata: rendered.namespace.metadata });
        const namespaceName = rendered.namespace.metadata.name;
        if (rendered.secret) {
            new Secret(this, "secret", {
                metadata: { ...rendered.secret.metadata, namespace: ns.metadata.name },
                // Plaintext: the provider base64-encodes `data` itself. The values were generated by the
                // backend and are never present in the spec that produced them.
                data: rendered.secret.data,
                type: rendered.secret.type,
            });
        }
        /**
         * Indexed rather than named, because a spec may declare several volumes and CDKTF ids must be
         * unique within a scope. The PVC's own name comes from the renderer, which is what the pod spec
         * already refers to.
         */
        rendered.pvcs.forEach((pvc, i) => {
            new PersistentVolumeClaim(this, `pvc-${i}`, {
                metadata: { ...pvc.metadata, namespace: ns.metadata.name },
                spec: pvc.spec,
                waitUntilBound: pvc.waitUntilBound,
            });
        });
        /**
         * The VPN sidecar mutates the pod spec in place, exactly as every hand-written construct does.
         * Applied here rather than in the renderer because it is a cluster concern that needs this
         * scope — and because the renderer is pure, which is what makes it testable.
         */
        const podSpec = rendered.deployment.spec.template.spec;
        VpnService.apply(this, ns.metadata.name, podSpec, config);
        new Deployment(this, "deployment", {
            ...rendered.deployment,
            metadata: { ...rendered.deployment.metadata, namespace: ns.metadata.name },
        });
        new Service(this, "service", {
            ...rendered.service,
            metadata: { ...rendered.service.metadata, namespace: ns.metadata.name },
        });
        // Only when the app has something a person would open. A database has no console, and an
        // ingress pointing at one would be a hostname that answers with a protocol error.
        if (rendered.ingressPort) {
            createAppIngress(this, "ingress", {
                namespace: namespaceName,
                serviceName: rendered.service.metadata.name,
                servicePort: rendered.ingressPort,
                hostname: `${namespaceName}.apps.local`,
            });
        }
        if (rendered.health) {
            createAppProbe(this, "probe", {
                namespace: namespaceName,
                serviceName: rendered.service.metadata.name,
                servicePort: rendered.health.port,
                path: rendered.health.path,
            });
        }
    }
}
