import React from 'react';

const ANSI_COLORS: Record<number, string> = {
  30: '#1e293b', 31: '#f87171', 32: '#4ade80', 33: '#facc15',
  34: '#60a5fa', 35: '#c084fc', 36: '#38bdf8', 37: '#e2e8f0',
  90: '#64748b', 91: '#ef4444', 92: '#22c55e', 93: '#eab308',
  94: '#3b82f6', 95: '#a855f7', 96: '#06b6d4', 97: '#f8fafc',
};

const BG_COLORS: Record<number, string> = {
  40: '#0f172a', 41: '#7f1d1d', 42: '#14532d', 43: '#713f12',
  44: '#1e3a5f', 45: '#581c87', 46: '#164e63', 47: '#334155',
  100: '#1e293b', 101: '#991b1b', 102: '#166534', 103: '#854d0e',
  104: '#1e40af', 105: '#6b21a8', 106: '#0e7490', 107: '#475569',
};

interface StyleState {
  fg?: string;
  bg?: string;
  bold?: boolean;
  dim?: boolean;
  italic?: boolean;
  underline?: boolean;
}

function isProgressStatusLine(line: string): boolean {
  const clean = line.replace(/[\u2800-\u28FF]/g, '').trim();
  if (!clean && line.trim().length > 0) {
    return true; // Line containing only a raw spinner character
  }
  return (
    clean.includes('Stack deploying') ||
    clean.includes('Stacks done') ||
    clean.includes('Stacks waiting') ||
    clean.includes('Synthesizing') ||
    clean.startsWith('Starting') ||
    clean.startsWith('Deploying') ||
    clean === 'Loading flow...' ||
    clean === 'Fetching Helm...' ||
    clean === 'Scanning cluster for errors...'
  );
}

/**
 * Pre-processes log text:
 * 1. Strips non-color ANSI control sequences (\x1b[2K, \x1b[1A, \x1b[G, etc.)
 * 2. Cleans orphan bracket control artifacts ([2K, [1A, [G, [?25h, [?25l)
 * 3. Strips raw Braille spinner characters (\u2800-\u28FF)
 * 4. Handles carriage returns (\r) line overwrites
 * 5. Collapses all progress/synthesizing status lines into a SINGLE in-place line
 */
function preprocessLogText(rawText: string): { lines: string[]; activeSpinnerIndex: number } {
  if (!rawText) return { lines: [], activeSpinnerIndex: -1 };

  // Strip non-color ANSI control sequences (e.g. \x1b[2K, \x1b[1A, \x1b[G, \x1b[?25h)
  let cleaned = rawText.replace(/\x1b\[[0-9;?]*[a-lno-zA-Z]/g, '');

  // Strip orphan control artifacts ([2K, [1A, [G, [?25h, etc.) if \x1b was stripped before reaching frontend
  cleaned = cleaned.replace(/\[[0-9;?]*[a-lno-zA-Z]/g, '');

  // Normalize CRLF
  cleaned = cleaned.replace(/\r\n/g, '\n');

  // Handle standalone CR (\r) line overwrites & strip Braille characters
  const rawLines = cleaned.split('\n');
  const processedLines: string[] = [];

  for (let line of rawLines) {
    if (line.includes('\r')) {
      const segments = line.split('\r').filter(s => s.length > 0);
      line = segments[segments.length - 1] || '';
    }

    // Strip raw Braille spinner characters
    const cleanLine = line.replace(/[\u2800-\u28FF]/g, '').trimEnd();

    // Skip empty lines generated by orphan spinner frame updates
    if (!cleanLine.trim() && line.replace(/[\u2800-\u28FF]/g, '').trim() === '') {
      continue;
    }

    processedLines.push(cleanLine);
  }

  // Keep exactly ONE progress status line across the log output
  const finalLines: string[] = [];
  let activeProgressIdx = -1;

  for (let i = 0; i < processedLines.length; i++) {
    const cur = processedLines[i]!;
    if (isProgressStatusLine(cur)) {
      if (activeProgressIdx !== -1) {
        // Overwrite the single existing progress status line with the newest update!
        finalLines[activeProgressIdx] = cur;
      } else {
        finalLines.push(cur);
        activeProgressIdx = finalLines.length - 1;
      }
    } else {
      finalLines.push(cur);
    }
  }

  return { lines: finalLines, activeSpinnerIndex: activeProgressIdx };
}

/**
 * Animated moving terminal spinner frame
 */
function TerminalSpinner() {
  const [frameIndex, setFrameIndex] = React.useState(0);
  const frames = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];

  React.useEffect(() => {
    const timer = setInterval(() => {
      setFrameIndex((prev) => (prev + 1) % frames.length);
    }, 80);
    return () => clearInterval(timer);
  }, []);

  return <span className="text-amber-400 font-bold mr-2 inline-block font-mono">{frames[frameIndex]}</span>;
}

/**
 * Line-level fallback syntax highlighter for CDKTF / Terraform / Helm / Kubectl logs
 * when explicit ANSI color escape codes are absent.
 */
function getFallbackLineStyle(line: string): StyleState | null {
  const trimmed = line.trim();

  // Section headers (e.g. "--- POD STATUS ---")
  if (/^-{2,}\s.+\s-{2,}$/.test(trimmed)) {
    return { fg: '#38bdf8', bold: true }; // Cyan
  }
  // Terraform / CDKTF diff additions
  if (trimmed.startsWith('+') || line.includes('will be created') || line.includes('Creation complete')) {
    return { fg: '#4ade80' }; // Emerald green
  }
  // Terraform / CDKTF diff deletions
  if (trimmed.startsWith('-') || line.includes('will be destroyed') || line.includes('Destruction complete')) {
    return { fg: '#f87171' }; // Soft red
  }
  // Terraform / CDKTF diff updates
  if (trimmed.startsWith('~') || line.includes('will be updated in-place')) {
    return { fg: '#facc15' }; // Amber yellow
  }
  // Plan summary / Outputs
  if (trimmed.startsWith('Plan:') || trimmed.startsWith('Changes to Outputs:') || trimmed.startsWith('Outputs:')) {
    return { fg: '#38bdf8', bold: true }; // Cyan
  }
  // Progress & Creating statuses
  if (line.includes('Creating...') || line.includes('Modifying...') || line.includes('Destroying...')) {
    return { fg: '#fbbf24' }; // Warm yellow
  }
  // Errors / Warnings
  if (line.includes('Error:') || line.includes('FAILED') || line.includes('panic:')) {
    return { fg: '#ef4444', bold: true }; // Bright Red
  }

  return null;
}

export function AnsiText({ text }: { text: string }) {
  if (!text) return null;

  const { lines, activeSpinnerIndex } = preprocessLogText(text);

  let globalKey = 0;
  const renderedLines: React.ReactNode[] = [];

  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const line = lines[lineIndex]!;
    const showSpinner = lineIndex === activeSpinnerIndex;
    const hasAnsiColor = /\x1b\[[0-9;]*m/.test(line);

    if (hasAnsiColor) {
      // Parse explicit ANSI color escape sequences
      const parts: { text: string; style: StyleState }[] = [];
      let pos = 0;
      let currentStyle: StyleState = {};
      const re = /\x1b\[([0-9;]*)m/g;

      while (true) {
        const match = re.exec(line);
        if (!match) break;

        if (match.index > pos) {
          parts.push({ text: line.slice(pos, match.index), style: { ...currentStyle } });
        }
        pos = re.lastIndex;

        const raw = match[1] || '';
        const codes = raw.split(';').map(Number);
        for (let cIdx = 0; cIdx < codes.length; cIdx++) {
          const code = codes[cIdx]!;
          if (code === 0) currentStyle = {};
          else if (code === 1) currentStyle.bold = true;
          else if (code === 2) currentStyle.dim = true;
          else if (code === 3) currentStyle.italic = true;
          else if (code === 4) currentStyle.underline = true;
          else if (ANSI_COLORS[code]) currentStyle.fg = ANSI_COLORS[code];
          else if (BG_COLORS[code]) currentStyle.bg = BG_COLORS[code];
          // 256-color support (38;5;n)
          else if ((code === 38 || code === 48) && codes[cIdx + 1] === 5 && codes[cIdx + 2] !== undefined) {
            const colorCode = codes[cIdx + 2]!;
            if (code === 38) currentStyle.fg = `hsl(${(colorCode * 16) % 360}, 70%, 65%)`;
            cIdx += 2;
          }
        }
      }

      if (pos < line.length) {
        parts.push({ text: line.slice(pos), style: { ...currentStyle } });
      }

      const lineSpans = parts.map((part) => {
        if (!part.text) return null;
        const s: React.CSSProperties = {};
        if (part.style.fg) s.color = part.style.fg;
        if (part.style.bg) s.backgroundColor = part.style.bg;
        if (part.style.bold) s.fontWeight = 'bold';
        if (part.style.dim) s.opacity = 0.6;
        if (part.style.italic) s.fontStyle = 'italic';
        if (part.style.underline) s.textDecoration = 'underline';
        return <span key={globalKey++} style={s}>{part.text}</span>;
      });

      renderedLines.push(
        <div key={lineIndex} className="min-h-[1.25em] flex items-center">
          {showSpinner && <TerminalSpinner />}
          <div>{lineSpans}</div>
        </div>
      );
    } else {
      // Fallback syntax highlighting for plain log lines
      const fallbackStyle = getFallbackLineStyle(line);
      const s: React.CSSProperties = {};
      if (fallbackStyle?.fg) s.color = fallbackStyle.fg;
      if (fallbackStyle?.bold) s.fontWeight = 'bold';

      renderedLines.push(
        <div key={lineIndex} style={s} className="min-h-[1.25em] flex items-center">
          {showSpinner && <TerminalSpinner />}
          <span>{line || ' '}</span>
        </div>
      );
    }
  }

  return <>{renderedLines}</>;
}