import type { AppType } from './app-types';

export const EMPTY_WIZARD_DATA = {
  name: 'Odoo-Production',
  clusterId: '',
  appType: 'odoo' as AppType,
  strategy: 'native' as 'helm' | 'native',
  odooRepo: 'library/odoo',
  odooTag: '18.0',
  pgRepo: 'library/postgres',
  pgTag: '16.4',
  modules: [] as string[],
  vpnEnabled: false,
  vpnProtocol: 'wireguard' as 'wireguard' | 'openvpn',
  vpnConfig: '',
  vpnDedicatedIp: '',
  vllmMaxModelLen: '',
  vllmGpuMemUtil: '',
  vllmExtraArgs: '',
  vllmToolCallingEnabled: false,
  vllmToolCallParser: '',
  vllmServedModelName: '',
  vllmMaxNumSeqs: '',
  vllmDtype: '',
  vllmEnablePrefixCaching: false,
  tabbyModel: 'turboderp/Qwen3.6-27B-exl3',
  tabbyRevision: '',
  tabbyGpuCount: '2',
  tabbyHfToken: '',
  tabbyImageTag: 'latest',
  tabbyCacheMode: 'Q8',
  tabbyMaxSeqLen: '32768',
  tabbyMaxBatchSize: '',
  tabbyReasoning: true,
  tabbyToolFormat: 'qwen3_coder',
  tabbyInlineModelLoading: false,
  tabbyDisableAuth: true,
  tabbyMemoryLimit: '',
  tabbyShmSize: '',
  tabbyCpuLimit: '10',
  tabbyExtraEnv: '',
  openWebuiTargetId: '',
  hermesTargetId: '',
  webuiEnableWebSearch: true,
  webuiWebSearchEngine: 'duckduckgo',
  webuiWebSearchApiKey: '',
  palworldPlayers: '16'
  };

export type WizardData = typeof EMPTY_WIZARD_DATA;
