apiVersion: v1
kind: Namespace
metadata:
  name: crawl4ai
  labels:
    name: crawl4ai
---
apiVersion: v1
kind: Secret
metadata:
  name: crawl4ai-secret
  namespace: crawl4ai
type: Opaque
stringData:
  api_token: "koala-dev-crawl4ai-token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl4ai
  namespace: crawl4ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawl4ai
  template:
    metadata:
      labels:
        app: crawl4ai
    spec:
      containers:
        - name: crawl4ai
          image: unclecode/crawl4ai:latest
          env:
            - name: CRAWL4AI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: crawl4ai-secret
                  key: api_token
            - name: CRAWL4AI_PORT
              value: "11235"
          ports:
            - containerPort: 11235
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
          resources:
            limits:
              memory: 4Gi
              cpu: 2000m
            requests:
              memory: 512Mi
              cpu: 200m
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: crawl4ai
  namespace: crawl4ai
spec:
  type: NodePort
  selector:
    app: crawl4ai
  ports:
    - port: 11235
      targetPort: 11235
      nodePort: 31235