import {
  handleListMcpServers, handleEnableMcpServer, handleAddProjectDependency, handleListInfrastructure,
  handleProposeSpec, handleGetLogs, handleListTrees, handleListTreeTypes, handleProposeTree, handleWebSearch,
  handleInspectResources, handleClusterCapacity, handleListClusters,
  handleGetProjectPipeline, handleDeployProject, handleDeployApp, handleGetProjectUrl, handleReadProjectPath,
  handleFetchWebPage, handleRequestEscalatedPrivileges, handleGetProjectEnv, handleSetProjectEnv,
  handleRequestSecret, handleInjectSecretToPod, handleGetProjectSecret, handleSetProjectSecret, handleListProjectSecrets,
  handleGetTreeType, handleCreateTreeType, handleSetTreeTypeOverview,
  handleSetTreeTypeScaffoldFile, handleDeleteTreeTypeScaffoldFile,
  handleAddValidationStep, handleAddValidationGroup, handleAddValidationLoop,
  handleReviseValidationStep, handleRemoveValidationStep, handleReorderValidationSteps,
  handleSetTreeTypeBindings, handleSetTreeTypeRoles, handleSetTreeTypeAutoAccept, handleSetTreeTypeVerdictPolicy, handleDeleteTreeType,
  handleAddWorkflowStage, handleAddWorkflowGroup, handleAddWorkflowLoop,
  handleReviseWorkflowStage, handleRemoveWorkflowStage, handleReorderWorkflowStages,
  type KoalaToolHandler,
} from './koala-tool-handlers.js';

export const KOALA_TOOL_HANDLERS = {
  list_mcp_servers: handleListMcpServers,
  enable_mcp_server: handleEnableMcpServer,
  add_project_dependency: handleAddProjectDependency,
  list_infrastructure: handleListInfrastructure,
  propose_spec: handleProposeSpec,
  get_logs: (ctx, args) => handleGetLogs(ctx, args, 'get_logs'),
  get_events: (ctx, args) => handleGetLogs(ctx, args, 'get_events'),
  inspect_resources: handleInspectResources,
  cluster_capacity: handleClusterCapacity,
  list_clusters: handleListClusters,
  list_trees: handleListTrees,
  list_tree_types: handleListTreeTypes,
  propose_tree: handleProposeTree,
  get_tree_type: handleGetTreeType,
  create_tree_type: handleCreateTreeType,
  set_tree_type_overview: handleSetTreeTypeOverview,
  set_tree_type_scaffold_file: handleSetTreeTypeScaffoldFile,
  delete_tree_type_scaffold_file: handleDeleteTreeTypeScaffoldFile,
  add_validation_step: handleAddValidationStep,
  add_validation_group: handleAddValidationGroup,
  add_validation_loop: handleAddValidationLoop,
  revise_validation_step: handleReviseValidationStep,
  remove_validation_step: handleRemoveValidationStep,
  reorder_validation_steps: handleReorderValidationSteps,
  set_tree_type_bindings: handleSetTreeTypeBindings,
  set_tree_type_roles: handleSetTreeTypeRoles,
  set_tree_type_auto_accept: handleSetTreeTypeAutoAccept,
  set_tree_type_verdict_policy: handleSetTreeTypeVerdictPolicy,
  delete_tree_type: handleDeleteTreeType,
  add_workflow_stage: handleAddWorkflowStage,
  add_workflow_group: handleAddWorkflowGroup,
  add_workflow_loop: handleAddWorkflowLoop,
  revise_workflow_stage: handleReviseWorkflowStage,
  remove_workflow_stage: handleRemoveWorkflowStage,
  reorder_workflow_stages: handleReorderWorkflowStages,
  get_project_pipeline: handleGetProjectPipeline,
  deploy_project: handleDeployProject,
  deploy_app: handleDeployApp,
  get_project_url: handleGetProjectUrl,
  read_project_path: handleReadProjectPath,
  request_escalated_privileges: handleRequestEscalatedPrivileges,
  get_project_env: handleGetProjectEnv,
  set_project_env: handleSetProjectEnv,
  request_secret: handleRequestSecret,
  inject_secret_to_pod: handleInjectSecretToPod,
  get_project_secret: handleGetProjectSecret,
  set_project_secret: handleSetProjectSecret,
  list_project_secrets: handleListProjectSecrets,
  web_search: handleWebSearch,
  fetch_web_page: handleFetchWebPage,
} satisfies Record<string, KoalaToolHandler>;

export type KoalaToolName = keyof typeof KOALA_TOOL_HANDLERS;

