export const ODOO_CHART_FILES: { path: string; content: string }[] = [
  {
    path: "deploy/chart/Chart.yaml",
    content: [
      "apiVersion: v2",
      "name: odoo-project",
      "description: An Odoo 18 project with two slots, A and B, on one PostgreSQL. One slot is live, the other is where the next version is prepared.",
      "type: application",
      "version: 0.1.0",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/values.yaml",
    content: [
      "# Set by the platform when it deploys: the image built from this repository, and the hosts the project answers on.",
      "image:",
      "  repository: \"\"",
      "  pullPolicy: IfNotPresent",
      "host: \"\"",
      "previewHost: \"\"",
      "",
      "# Which slot serves the project's host. The other slot is where a new version is prepared and previewed.",
      "live: a",
      "slots:",
      "  a:",
      "    tag: \"\"",
      "  b:",
      "    tag: \"\"",
      "",
      "postgres:",
      "  image: postgres:17",
      "  storage: 5Gi",
      "  resources:",
      "    requests: { cpu: 100m, memory: 256Mi }",
      "    limits: { memory: 1Gi }",
      "",
      "# Attachments for both slots: Odoo keeps each database's files under filestore/<database>.",
      "filestore:",
      "  storage: 5Gi",
      "",
      "odoo:",
      "  workers: 0",
      "  resources:",
      "    requests: { cpu: 100m, memory: 512Mi }",
      "    limits: { memory: 2Gi }",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/templates/_helpers.tpl",
    content: [
      "{{- define \"odoo-project.name\" -}}{{ .Release.Name }}{{- end -}}",
      "{{- define \"odoo-project.labels\" -}}",
      "app.kubernetes.io/name: odoo-project",
      "app.kubernetes.io/instance: {{ .Release.Name }}",
      "{{- end -}}",
      "{{- define \"odoo-project.idle\" -}}{{ if eq .Values.live \"a\" }}b{{ else }}a{{ end }}{{- end -}}",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/templates/secret.yaml",
    content: [
      "{{- $name := printf \"%s-secrets\" (include \"odoo-project.name\" .) }}",
      "{{- $existing := lookup \"v1\" \"Secret\" .Release.Namespace $name }}",
      "apiVersion: v1",
      "kind: Secret",
      "metadata:",
      "  name: {{ $name }}",
      "  labels: {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "  annotations:",
      "    helm.sh/resource-policy: keep",
      "type: Opaque",
      "data:",
      "  {{- if $existing }}",
      "  postgres-password: {{ index $existing.data \"postgres-password\" }}",
      "  {{- else }}",
      "  postgres-password: {{ randAlphaNum 32 | b64enc }}",
      "  {{- end }}",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/templates/postgres.yaml",
    content: [
      "{{- $name := include \"odoo-project.name\" . }}",
      "apiVersion: v1",
      "kind: Service",
      "metadata:",
      "  name: {{ $name }}-postgres",
      "  labels: {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "spec:",
      "  selector:",
      "    {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "    app.kubernetes.io/component: postgres",
      "  ports:",
      "    - name: postgres",
      "      port: 5432",
      "      targetPort: 5432",
      "---",
      "apiVersion: apps/v1",
      "kind: StatefulSet",
      "metadata:",
      "  name: {{ $name }}-postgres",
      "  labels: {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "spec:",
      "  serviceName: {{ $name }}-postgres",
      "  replicas: 1",
      "  selector:",
      "    matchLabels:",
      "      {{- include \"odoo-project.labels\" . | nindent 6 }}",
      "      app.kubernetes.io/component: postgres",
      "  template:",
      "    metadata:",
      "      labels:",
      "        {{- include \"odoo-project.labels\" . | nindent 8 }}",
      "        app.kubernetes.io/component: postgres",
      "    spec:",
      "      containers:",
      "        - name: postgres",
      "          image: {{ .Values.postgres.image }}",
      "          env:",
      "            - name: POSTGRES_USER",
      "              value: odoo",
      "            - name: POSTGRES_DB",
      "              value: postgres",
      "            - name: POSTGRES_PASSWORD",
      "              valueFrom:",
      "                secretKeyRef: { name: {{ $name }}-secrets, key: postgres-password }",
      "            - name: PGDATA",
      "              value: /var/lib/postgresql/data/pgdata",
      "          ports:",
      "            - containerPort: 5432",
      "          readinessProbe:",
      "            exec:",
      "              command: [\"pg_isready\", \"-U\", \"odoo\"]",
      "            periodSeconds: 5",
      "          resources: {{- toYaml .Values.postgres.resources | nindent 12 }}",
      "          volumeMounts:",
      "            - name: data",
      "              mountPath: /var/lib/postgresql/data",
      "  volumeClaimTemplates:",
      "    - metadata:",
      "        name: data",
      "      spec:",
      "        accessModes: [\"ReadWriteOnce\"]",
      "        resources:",
      "          requests:",
      "            storage: {{ .Values.postgres.storage }}",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/templates/filestore.yaml",
    content: [
      "apiVersion: v1",
      "kind: PersistentVolumeClaim",
      "metadata:",
      "  name: {{ include \"odoo-project.name\" . }}-filestore",
      "  labels: {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "  annotations:",
      "    helm.sh/resource-policy: keep",
      "spec:",
      "  accessModes: [\"ReadWriteOnce\"]",
      "  resources:",
      "    requests:",
      "      storage: {{ .Values.filestore.storage }}",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/templates/odoo.yaml",
    content: [
      "{{- $root := . }}",
      "{{- $name := include \"odoo-project.name\" . }}",
      "{{- range $slot := list \"a\" \"b\" }}",
      "{{- $tag := (index $root.Values.slots $slot).tag }}",
      "{{- if $tag }}",
      "---",
      "apiVersion: v1",
      "kind: Service",
      "metadata:",
      "  name: {{ $name }}-odoo-{{ $slot }}",
      "  labels: {{- include \"odoo-project.labels\" $root | nindent 4 }}",
      "spec:",
      "  selector:",
      "    {{- include \"odoo-project.labels\" $root | nindent 4 }}",
      "    app.kubernetes.io/component: odoo",
      "    koala.dev/slot: {{ $slot }}",
      "  ports:",
      "    - name: http",
      "      port: 8069",
      "      targetPort: 8069",
      "---",
      "apiVersion: apps/v1",
      "kind: Deployment",
      "metadata:",
      "  name: {{ $name }}-odoo-{{ $slot }}",
      "  labels:",
      "    {{- include \"odoo-project.labels\" $root | nindent 4 }}",
      "    app.kubernetes.io/component: odoo",
      "    koala.dev/slot: {{ $slot }}",
      "spec:",
      "  replicas: 1",
      "  strategy:",
      "    type: Recreate",
      "  selector:",
      "    matchLabels:",
      "      {{- include \"odoo-project.labels\" $root | nindent 6 }}",
      "      app.kubernetes.io/component: odoo",
      "      koala.dev/slot: {{ $slot }}",
      "  template:",
      "    metadata:",
      "      labels:",
      "        {{- include \"odoo-project.labels\" $root | nindent 8 }}",
      "        app.kubernetes.io/component: odoo",
      "        koala.dev/slot: {{ $slot }}",
      "    spec:",
      "      securityContext:",
      "        fsGroup: 101",
      "      containers:",
      "        - name: odoo",
      "          image: \"{{ $root.Values.image.repository }}:{{ $tag }}\"",
      "          imagePullPolicy: {{ $root.Values.image.pullPolicy }}",
      "          args:",
      "            - --database=odoo_{{ $slot }}",
      "            - --db-filter=^odoo_{{ $slot }}$",
      "            - --no-database-list",
      "            - --proxy-mode",
      "            - --workers={{ $root.Values.odoo.workers }}",
      "            - --data-dir=/var/lib/odoo",
      "          env:",
      "            - name: HOST",
      "              value: {{ $name }}-postgres",
      "            - name: USER",
      "              value: odoo",
      "            - name: PASSWORD",
      "              valueFrom:",
      "                secretKeyRef: { name: {{ $name }}-secrets, key: postgres-password }",
      "          ports:",
      "            - containerPort: 8069",
      "          readinessProbe:",
      "            httpGet: { path: /web/health, port: 8069 }",
      "            periodSeconds: 10",
      "            failureThreshold: 30",
      "          resources: {{- toYaml $root.Values.odoo.resources | nindent 12 }}",
      "          volumeMounts:",
      "            - name: filestore",
      "              mountPath: /var/lib/odoo",
      "      volumes:",
      "        - name: filestore",
      "          persistentVolumeClaim:",
      "            claimName: {{ $name }}-filestore",
      "{{- end }}",
      "{{- end }}",
    ].join('\n') + '\n',
  },
  {
    path: "deploy/chart/templates/ingress.yaml",
    content: [
      "{{- $name := include \"odoo-project.name\" . }}",
      "{{- $idle := include \"odoo-project.idle\" . }}",
      "{{- if .Values.host }}",
      "apiVersion: v1",
      "kind: Service",
      "metadata:",
      "  name: {{ $name }}-live",
      "  labels: {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "spec:",
      "  selector:",
      "    {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "    app.kubernetes.io/component: odoo",
      "    koala.dev/slot: {{ .Values.live }}",
      "  ports:",
      "    - name: http",
      "      port: 8069",
      "      targetPort: 8069",
      "---",
      "apiVersion: networking.k8s.io/v1",
      "kind: Ingress",
      "metadata:",
      "  name: app",
      "  labels: {{- include \"odoo-project.labels\" . | nindent 4 }}",
      "spec:",
      "  ingressClassName: traefik",
      "  rules:",
      "    - host: {{ .Values.host }}",
      "      http:",
      "        paths:",
      "          - path: /",
      "            pathType: Prefix",
      "            backend:",
      "              service:",
      "                name: {{ $name }}-live",
      "                port: { number: 8069 }",
      "    {{- if and .Values.previewHost (index .Values.slots $idle).tag }}",
      "    - host: {{ .Values.previewHost }}",
      "      http:",
      "        paths:",
      "          - path: /",
      "            pathType: Prefix",
      "            backend:",
      "              service:",
      "                name: {{ $name }}-odoo-{{ $idle }}",
      "                port: { number: 8069 }",
      "    {{- end }}",
      "{{- end }}",
    ].join('\n') + '\n',
  },
];
