import type { TreeTypeSeed } from './tree-types.js';
import {
  NODE_SERVICE_FILES,
  MCP_SERVER_FILES,
  LIBRARY_FILES,
  UI_APP_FILES,
  RESEARCH_PAPER_FILES,
  DECISION_BRIEF_FILES,
  DATASET_FILES,
  BENCHMARK_FILES,
  INVESTIGATION_FILES,
  MCP_SERVER_RECIPE,
  NODE_SERVICE_RECIPE,
  UI_APP_RECIPE,
  RESEARCH_PAPER_RECIPE,
  DECISION_BRIEF_RECIPE,
  DATASET_RECIPE,
  LIBRARY_RECIPE,
  BENCHMARK_RECIPE,
  INVESTIGATION_RECIPE,
  MIGRATION_RECIPE,
} from './project-templates.js';

export const TREE_TYPE_SEEDS: TreeTypeSeed[] = [
  {
    id: 'mcp-server',
    label: 'MCP server',
    summary: 'A service exposing tools over MCP, callable by this platform and by other agents.',
    language: 'node',
    produces: 'service',
    doneMeans: 'It builds, it deploys, it answers `initialize`, and its tools return real data when called.',
    files: MCP_SERVER_FILES,
    validationRecipe: MCP_SERVER_RECIPE,
    defaultBindings: ['gitea'],
  },
  {
    id: 'ui-app',
    label: 'UI application',
    summary: 'Interactive web frontend application built with React and Vite.',
    language: 'node',
    produces: 'service',
    doneMeans: 'The frontend builds cleanly, dist/index.html is produced, and the web UI renders and serves.',
    files: UI_APP_FILES,
    validationRecipe: UI_APP_RECIPE,
  },
  {
    id: 'api-service',
    language: 'node',
    produces: 'service',
    label: 'API / service',
    summary: 'Something that runs and answers requests.',
    doneMeans: 'Its tests pass, it builds, it deploys, and the endpoint responds.',
    files: NODE_SERVICE_FILES,
    validationRecipe: NODE_SERVICE_RECIPE,
  },
  {
    id: 'research-paper',
    language: 'base',
    produces: 'artefact',
    label: 'Research paper',
    summary: 'A written answer with sources — a comparison, a survey, a recommendation.',
    doneMeans: 'Every question is answered, every claim carries a source, and the write-up reads as one piece.',
    files: RESEARCH_PAPER_FILES,
    validationRecipe: RESEARCH_PAPER_RECIPE,
  },
  {
    id: 'decision-brief',
    language: 'base',
    produces: 'artefact',
    label: 'Decision brief',
    summary: 'Options compared against criteria, ending in a recommendation.',
    doneMeans: 'Every option is covered against every criterion, and every claim is cited.',
    files: DECISION_BRIEF_FILES,
    validationRecipe: DECISION_BRIEF_RECIPE,
  },
  {
    id: 'library',
    language: 'node',
    produces: 'artefact',
    label: 'Library / CLI',
    summary: 'Code other things import or run. No deployment.',
    doneMeans: 'Its tests pass and it installs cleanly from a fresh checkout.',
    files: LIBRARY_FILES,
    validationRecipe: LIBRARY_RECIPE,
  },
  {
    id: 'dataset',
    language: 'python',
    produces: 'artefact',
    label: 'Dataset',
    summary: 'Data collected, cleaned and labelled, with provenance.',
    doneMeans: 'The schema validates, the row counts are what was promised, and every row can say where it came from.',
    files: DATASET_FILES,
    validationRecipe: DATASET_RECIPE,
  },
  {
    id: 'benchmark',
    language: 'node',
    produces: 'artefact',
    label: 'Benchmark',
    summary: 'A task set, run across variants, compared.',
    doneMeans: 'Every run completed, the metrics are produced, and the spread between runs is reported.',
    files: BENCHMARK_FILES,
    validationRecipe: BENCHMARK_RECIPE,
  },
  {
    id: 'investigation',
    language: 'node',
    produces: 'artefact',
    label: 'Investigation',
    summary: 'Why something is broken or slow, and what to do about it.',
    doneMeans: 'There is a reproduction that fails before the fix and passes after it.',
    files: INVESTIGATION_FILES,
    validationRecipe: INVESTIGATION_RECIPE,
  },
  {
    id: 'migration',
    language: 'node',
    produces: 'artefact',
    label: 'Migration / refactor',
    summary: 'A bounded change across code that already exists.',
    doneMeans: 'The existing test suite still passes and behaviour is unchanged.',
    validationRecipe: MIGRATION_RECIPE,
    files: [],
  },
  {
    id: 'data-analysis',
    language: 'python',
    produces: 'artefact',
    label: 'Data analysis',
    summary: 'Load, analyse, and report — charts and conclusions.',
    doneMeans: 'The analysis runs end to end from a clean checkout and produces its outputs.',
    files: [],
  },
  {
    id: 'docs-site',
    language: 'node',
    produces: 'service',
    label: 'Documentation',
    summary: 'Documentation derived from a codebase.',
    doneMeans: 'Links resolve and the code examples actually run.',
    files: [],
  },
  {
    id: 'infra-module',
    language: 'node',
    produces: 'artefact',
    label: 'Infrastructure module',
    summary: 'A reusable piece of infrastructure.',
    doneMeans: 'It provisions, verifies, and destroys again without leaving anything behind.',
    files: [],
  },
];
