import type { HostOperation } from '@koala/agent-engine/procedure';

const NONE = { type: 'object', properties: {} } as const;
const TREE = { name: 'tree', type: 'json', describe: 'The tree, as Open Tree hands it on.', required: true } as const;
const ENVIRONMENT = { name: 'environment', type: 'environment', describe: 'The tree\'s shared workspace, as Open Tree hands it on.', required: true } as const;
const LEAF = { name: 'leaf', type: 'json', describe: 'The leaf being worked — the item a fan-out handed this run, or the leaf itself.', required: true } as const;

export const GROVE_OPERATIONS: readonly HostOperation[] = [
  {
    name: 'grove.open-tree',
    title: 'Open Tree',
    group: 'Grove',
    describe: 'Opens the tree this run grows and its one shared workspace, and puts back any leaf a stopped run left running. The workspace image holds what every agent this procedure can start needs.',
    inputs: [{ name: 'treeId', type: 'text', describe: 'Which tree. Nothing wired means the treeId the run was started with.' }],
    outputs: [
      { name: 'tree', type: 'json', describe: 'The tree: its id, name and type.' },
      { name: 'environment', type: 'environment', describe: 'The tree\'s shared workspace, for every stage to work in.' },
      { name: 'reset', type: 'json', describe: 'The leaves that were left running and are waiting again.' },
      { name: 'reason', type: 'text', describe: 'Why the tree could not be opened, when it could not.' },
    ],
    exits: [
      { name: 'ready', describe: 'The tree and its workspace are open.' },
      { name: 'unavailable', describe: 'There is no such tree, or its workspace could not be had.' },
    ],
    settings: NONE,
    summary: 'opens the tree and its shared workspace',
    idempotent: true,
  },
  {
    name: 'grove.leaves',
    title: 'Leaves',
    group: 'Grove',
    describe: 'Reads where every leaf of the tree stands and says what comes next: work the leaves that are ready, judge the claims that are in, or nothing — the tree is quiet.',
    inputs: [TREE],
    outputs: [
      { name: 'ready', type: 'json', describe: 'Leaves whose dependencies are met and that have tasks.' },
      { name: 'claimed', type: 'json', describe: 'Leaves claimed and waiting for a judge.' },
      { name: 'awaitingReview', type: 'json', describe: 'Claims a judge left for a person.' },
      { name: 'unbroken', type: 'json', describe: 'Leaves with no tasks yet.' },
      { name: 'blocked', type: 'json', describe: 'Leaves waiting on others.' },
      { name: 'settled', type: 'json', describe: 'Leaves that succeeded, failed or were cancelled.' },
    ],
    exits: [
      { name: 'work', describe: 'Some leaves are ready to be worked.' },
      { name: 'judge', describe: 'Nothing is ready, and some claims wait for a judge.' },
      { name: 'quiet', describe: 'Nothing is ready and nothing is claimed.' },
    ],
    settings: NONE,
    summary: 'reads where the leaves stand',
    idempotent: true,
  },
  {
    name: 'grove.prepare-worktrees',
    title: 'Prepare Worktrees',
    group: 'Grove',
    describe: 'Gives each leaf its own worktree of the shared workspace, on its own branch, holding what the leaves it waits on committed. A leaf being replanned gets the document saying why, committed in its worktree. A leaf whose worktree cannot be made is failed, with the reason.',
    inputs: [ENVIRONMENT, TREE, { name: 'leaves', type: 'json', describe: 'The leaves, from Leaves or Needs Plan.', required: true }],
    outputs: [
      { name: 'items', type: 'json', describe: 'One item per prepared leaf: what came in, plus its worktree — ready for a fan-out.' },
      { name: 'failed', type: 'json', describe: 'The leaves that could not be prepared, each with why.' },
    ],
    exits: [
      { name: 'ready', describe: 'At least one leaf has its worktree.' },
      { name: 'none', describe: 'No leaf could be prepared.' },
    ],
    settings: NONE,
    summary: 'gives each leaf its own worktree',
    idempotent: true,
  },
  {
    name: 'grove.start-leaf',
    title: 'Start Leaf',
    group: 'Grove',
    describe: 'Marks the leaf running, if it is still waiting to be worked.',
    inputs: [LEAF],
    outputs: [{ name: 'leaf', type: 'json', describe: 'The leaf, as it now stands.' }],
    exits: [
      { name: 'started', describe: 'The leaf is running.' },
      { name: 'notWaiting', describe: 'The leaf was no longer waiting — someone else has it, or it was settled.' },
    ],
    settings: NONE,
    summary: 'marks the leaf running',
    idempotent: true,
  },
  {
    name: 'grove.next-task',
    title: 'Next Task',
    group: 'Grove',
    describe: 'Says what the leaf needs next: the next task to hand an executor (with what its last attempt left), that every task is finished and the leaf can be claimed, that it cannot finish, or that it has no tasks yet.',
    inputs: [LEAF],
    outputs: [
      { name: 'task', type: 'json', describe: 'The task to work, ready to hand an executor.' },
      { name: 'reason', type: 'text', describe: 'Why the leaf cannot finish, when it cannot.' },
    ],
    exits: [
      { name: 'run', describe: 'A task is ready to work.' },
      { name: 'claim', describe: 'Every task is finished.' },
      { name: 'fail', describe: 'A task used the attempts it was allowed, or can never start.' },
      { name: 'unbroken', describe: 'The leaf has no tasks yet.' },
    ],
    settings: {
      type: 'object',
      properties: {
        taskAttempts: { type: 'integer', title: 'Attempts per task', describe: 'How many times a failed task is worked before the leaf fails. Empty is as many as it takes.', minimum: 1 },
      },
    },
    summary: 'asks what the leaf needs next (attempts: {{taskAttempts}})',
    idempotent: true,
  },
  {
    name: 'grove.file-claim',
    title: 'File Claim',
    group: 'Grove',
    describe: 'Files the leaf\'s claim: that it is done, with the evidence for its judge, or that it failed, with why. Work left uncommitted in the worktree is committed first, so the claim points at all of it.',
    inputs: [
      LEAF,
      ENVIRONMENT,
      { name: 'evidence', type: 'text', describe: 'What the work run said for itself, for a leaf worked in one run.' },
      { name: 'reason', type: 'text', describe: 'Why the leaf failed, for a failed claim.' },
    ],
    outputs: [
      { name: 'claim', type: 'json', describe: 'The claim as filed.' },
      { name: 'reason', type: 'text', describe: 'Why the claim was refused, when it was.' },
    ],
    exits: [
      { name: 'filed', describe: 'The claim is on file.' },
      { name: 'refused', describe: 'The claim could not be filed.' },
    ],
    settings: {
      type: 'object',
      required: ['result'],
      properties: { result: { type: 'string', title: 'Claim', enum: ['claimed', 'failed'], default: 'claimed' } },
    },
    summary: 'files the leaf as {{result}}',
    idempotent: false,
  },
  {
    name: 'grove.return-leaf',
    title: 'Return Leaf',
    group: 'Grove',
    describe: 'Puts a running leaf back to waiting — for the planner when it turned out to have no tasks, or when its run was stopped. A leaf that has moved on is left alone.',
    inputs: [LEAF],
    outputs: [],
    exits: [{ name: 'done', describe: 'The leaf is waiting again, or had already moved on.' }],
    settings: NONE,
    summary: 'puts the leaf back to waiting',
    idempotent: true,
  },
  {
    name: 'grove.check-claims',
    title: 'Check Claims',
    group: 'Grove',
    describe: 'Runs the checks each claimed leaf\'s tasks carry, in the commit the claim points at. A claim whose checks fail is settled against there and then, with the report as its reason; only the rest go on to a judge.',
    inputs: [ENVIRONMENT, TREE, { name: 'claimed', type: 'json', describe: 'The claimed leaves, from Leaves.', required: true }],
    outputs: [
      { name: 'toJudge', type: 'json', describe: 'The claims whose checks passed, or that carry none.' },
      { name: 'settled', type: 'json', describe: 'The claims settled by their checks, each with the report.' },
    ],
    exits: [
      { name: 'judge', describe: 'Some claims are left for a judge.' },
      { name: 'settled', describe: 'Every claim was settled by its checks.' },
    ],
    settings: NONE,
    summary: 'runs the checks each claim carries',
    idempotent: false,
  },
  {
    name: 'grove.judge-checkouts',
    title: 'Judge Checkouts',
    group: 'Grove',
    describe: 'Gives each claim a clean checkout of exactly the commit it points at, so its judge reads what the leaf did and nothing else.',
    inputs: [ENVIRONMENT, TREE, { name: 'claims', type: 'json', describe: 'The claims to judge.', required: true }],
    outputs: [{ name: 'items', type: 'json', describe: 'One item per claim — the leaf, the claim and the checkout — ready for a judge.' }],
    exits: [{ name: 'ready', describe: 'Every claim has its checkout.' }],
    settings: NONE,
    summary: 'checks out each claim for its judge',
    idempotent: true,
  },
  {
    name: 'grove.needs-plan',
    title: 'Needs Plan',
    group: 'Grove',
    describe: 'Finds the leaves a planner should look at: failed leaves to replan, with everything that went wrong, and leaves with no tasks to break down. A leaf with a proposal already waiting is left alone.',
    inputs: [TREE],
    outputs: [{ name: 'items', type: 'json', describe: 'One item per leaf to plan, ready for Prepare Worktrees and then a planner.' }],
    exits: [
      { name: 'some', describe: 'Some leaves need a planner.' },
      { name: 'none', describe: 'No leaf needs one.' },
    ],
    settings: {
      type: 'object',
      properties: {
        replans: { type: 'integer', title: 'Replans per leaf', describe: 'How many times a failed leaf is replanned before it is left for a person. Empty is as many as it takes; 0 is never.', minimum: 0 },
      },
    },
    summary: 'finds leaves to replan or break down (replans: {{replans}})',
    idempotent: true,
  },
  {
    name: 'grove.open-proposals',
    title: 'Open Proposals',
    group: 'Grove',
    describe: 'The plans for this tree\'s leaves that are waiting for a person to approve them.',
    inputs: [TREE],
    outputs: [{ name: 'proposals', type: 'json', describe: 'The waiting proposals\' ids.' }],
    exits: [
      { name: 'some', describe: 'Some proposals wait for a person.' },
      { name: 'none', describe: 'None do.' },
    ],
    settings: NONE,
    summary: 'lists the plans waiting for a person',
    idempotent: true,
  },
  {
    name: 'grove.park-tree',
    title: 'Park Tree',
    group: 'Grove',
    describe: 'Parks the tree\'s workspace when the run is over, keeping its repository for the next run.',
    inputs: [TREE],
    outputs: [],
    exits: [{ name: 'done', describe: 'The workspace is parked.' }],
    settings: NONE,
    summary: 'parks the tree\'s workspace',
    idempotent: true,
  },
  {
    name: 'grove.report',
    title: 'Grove Report',
    group: 'Grove',
    describe: 'What the run comes to, in the shape the tree page shows: how it ended, the claims left for a person, and the plans waiting for approval.',
    inputs: [
      TREE,
      { name: 'awaitingReview', type: 'json', describe: 'Claims a judge left for a person, from Leaves.' },
      { name: 'proposals', type: 'json', describe: 'Plans waiting for approval, from Open Proposals.' },
    ],
    outputs: [{ name: 'result', type: 'json', describe: 'The run\'s result, for the Finish node.' }],
    exits: [{ name: 'done', describe: 'The report is ready.' }],
    settings: {
      type: 'object',
      required: ['outcome'],
      properties: { outcome: { type: 'string', title: 'Outcome', enum: ['quiet', 'stopped'], default: 'quiet' } },
    },
    summary: 'reports the run as {{outcome}}',
    idempotent: true,
  },
];
