apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "instance.name" . }}-data
  labels: {{- include "instance.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.data }}
