{{- if .Values.instance.credential }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instance.name" . }}-instance
  labels: {{- include "instance.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  INSTANCE_CREDENTIAL: {{ .Values.instance.credential | quote }}
{{- end }}
