apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instance.name" . }}-keys
  labels: {{- include "instance.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  SESSION_KEY: {{ include "instance.secret" (dict "root" . "key" "SESSION_KEY" "length" 64) }}
  DATA_KEY: {{ include "instance.secret" (dict "root" . "key" "DATA_KEY" "length" 64) }}
  PAYLOAD_KEY: {{ include "instance.secret" (dict "root" . "key" "PAYLOAD_KEY" "length" 64) }}
  EGRESS_KEY: {{ include "instance.secret" (dict "root" . "key" "EGRESS_KEY" "length" 64) }}
  MONGO_ROOT_PASSWORD: {{ include "instance.secret" (dict "root" . "key" "MONGO_ROOT_PASSWORD" "length" 40) }}
  TEMPORAL_DB_PASSWORD: {{ include "instance.secret" (dict "root" . "key" "TEMPORAL_DB_PASSWORD" "length" 40) }}
