import type { ToolDefinition } from '@koala/agent-engine';

export const CHECK_TOOLS: ToolDefinition[] = [
  {
    name: 'list_checks',
    summary: 'List the person\'s checks — all of them, or those of one agent, tool or procedure — with how each last went',
    guidance: 'Use this before writing a check, to see what is already covered and to reuse a check\'s shape. Narrow it to the agent, tool or procedure the check is about.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: false,
    returns: 'one line per check: its id, level, who plays the model, the agent, whether it is the person\'s own, its last result, and its name',
    failures: [{ when: 'more than one of agent, tool and procedure is given', says: 'so, and lists nothing' }],
    parameters: {
      type: 'object',
      properties: {
        agent: { type: 'string', description: 'Only the checks of this agent.' },
        tool: { type: 'string', description: 'Only the checks that call or expect this tool.' },
        procedure: { type: 'string', description: 'Only the checks of this procedure.' },
      },
    },
  },
  {
    name: 'read_check',
    summary: 'Read one check in full, and what happened the last time it ran',
    guidance: 'Use this to see exactly how a check is written before changing it or writing one like it.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: false,
    returns: 'the check as JSON, and its last result check by check',
    failures: [{ when: 'there is no check with that id', says: 'so' }],
    parameters: {
      type: 'object',
      properties: { id: { type: 'string', description: 'The check\'s id.' } },
      required: ['id'],
    },
  },
  {
    name: 'write_check',
    summary: 'Save a new check as the person\'s own',
    guidance: 'Send the whole check. It is checked the way the Checks page checks it; when something does not hold, nothing is saved and every problem is listed — fix them and send it again. It never replaces a check that exists: change one of the person\'s with update_check, or give yours its own id.',
    binding: 'platform',
    effect: 'write',
    idempotent: true,
    destructive: false,
    openWorld: false,
    returns: 'that the check was saved, with its id, or every problem that stopped it',
    failures: [
      { when: 'the check does not hold together', says: 'every problem, so all can be fixed at once' },
      { when: 'a check with that id exists', says: 'so, and saves nothing' },
    ],
    parameters: {
      type: 'object',
      properties: {
        check: { type: 'object', description: 'The whole check: id, name, describe, agent, procedure, input, expect, and world, script, step or then when it needs them.' },
      },
      required: ['check'],
    },
  },
  {
    name: 'update_check',
    summary: 'Replace one of the person\'s own checks with a changed version',
    guidance: 'Send the whole check, with the id of the one it replaces. The version it replaces is gone afterwards, so the person is asked first. Built-in checks cannot be changed.',
    binding: 'platform',
    effect: 'write',
    idempotent: true,
    destructive: true,
    openWorld: false,
    returns: 'that the check was replaced, or every problem that stopped it',
    failures: [
      { when: 'the person has no check of their own with that id', says: 'so, and saves nothing' },
      { when: 'the check does not hold together', says: 'every problem, so all can be fixed at once' },
    ],
    parameters: {
      type: 'object',
      properties: {
        check: { type: 'object', description: 'The whole changed check, with the id of the one it replaces.' },
      },
      required: ['check'],
    },
  },
  {
    name: 'run_check',
    summary: 'Run one check in a fresh space, on the person\'s model unless the check has a script',
    guidance: 'Use this after writing a check, to see it pass or fail. A scripted check takes seconds; one on the person\'s model can take minutes. It returns at once; read the outcome with read_check_result.',
    binding: 'platform',
    effect: 'write',
    idempotent: false,
    destructive: false,
    openWorld: false,
    returns: 'the id of the run to read with read_check_result',
    failures: [{ when: 'there is no check with that id', says: 'so, and runs nothing' }],
    parameters: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'The check\'s id.' },
        modelId: { type: 'string', description: 'A model to run it on instead of the person\'s default.' },
      },
      required: ['id'],
    },
  },
  {
    name: 'read_check_result',
    summary: 'Read how a check run went, or that it is still running',
    guidance: 'Use this after run_check. When it says it is still running, wait and read it again.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: false,
    returns: 'still running, or each check passed or failed with why, the tools the run called, and the run to read for more',
    failures: [{ when: 'there is no run with that id', says: 'so' }],
    parameters: {
      type: 'object',
      properties: { runId: { type: 'string', description: 'The id run_check returned.' } },
      required: ['runId'],
    },
  },
  {
    name: 'delete_check',
    summary: 'Delete one of the person\'s own checks',
    guidance: 'Only for a check you wrote that turned out wrong or redundant. Built-in checks cannot be deleted.',
    binding: 'platform',
    effect: 'write',
    idempotent: true,
    destructive: true,
    openWorld: false,
    returns: 'that it was deleted',
    failures: [{ when: 'the person has no check of their own with that id', says: 'so' }],
    parameters: {
      type: 'object',
      properties: { id: { type: 'string', description: 'The check\'s id.' } },
      required: ['id'],
    },
  },
];
