import type { ToolDefinition } from '@koala/agent-engine';

const NO_DEPLOYMENT = { when: 'the deployment is not one of yours', says: 'the names of the deployments that are' };

export const KUBE_TOOLS: ToolDefinition[] = [
  {
    name: 'list_infrastructure',
    summary: 'List the person\'s clusters — provider, state, size — and what is deployed on each, with its state',
    guidance: 'Use this to answer what exists and where, or to find the name of a deployment or cluster the other diagnostics need.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: false,
    status: 'draft',
    returns: 'one line per cluster, then its deployments as `- <name>: <app type>, <state> — <why it is unhealthy>`',
    failures: [{ when: 'there are no clusters', says: 'so' }],
    parameters: { type: 'object', properties: {} },
  },
  {
    name: 'get_logs',
    summary: 'Read the recent logs (last 60 lines per container) of one of the person\'s deployments',
    guidance: 'Use this when a deployment misbehaves and its output would show why. A container that never started has no logs; its events do.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: true,
    status: 'draft',
    returns: 'the log lines, each prefixed with its pod and container, or that there were none',
    failures: [NO_DEPLOYMENT, { when: 'the cluster cannot be reached', says: 'could not read, and why' }],
    parameters: {
      type: 'object',
      properties: { deployment: { type: 'string', description: 'The deployment\'s name, as list_infrastructure shows it.' } },
      required: ['deployment'],
    },
  },
  {
    name: 'get_events',
    summary: 'Read the recent Kubernetes events of one of the person\'s deployments — scheduling, image pulls, crashes, probes',
    guidance: 'Use this when a deployment will not start or keeps restarting: events say why a pod is pending, cannot pull its image, or is killed.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: true,
    status: 'draft',
    returns: 'the events, oldest first, or that there were none',
    failures: [NO_DEPLOYMENT, { when: 'the cluster cannot be reached', says: 'could not read, and why' }],
    parameters: {
      type: 'object',
      properties: { deployment: { type: 'string', description: 'The deployment\'s name, as list_infrastructure shows it.' } },
      required: ['deployment'],
    },
  },
  {
    name: 'inspect_resources',
    summary: 'Look at Kubernetes objects read-only — get, describe or top pods, deployments, services, volumes, events; or nodes, volumes and namespaces of a cluster',
    guidance: 'Use this for detail the logs and events do not give: a pod\'s state, a service\'s ports, a volume\'s size. It cannot change anything, and Secrets and ConfigMaps cannot be read.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: true,
    status: 'draft',
    returns: 'the kubectl output for that read',
    failures: [
      NO_DEPLOYMENT,
      { when: 'the verb is not get, describe or top', says: 'which verbs can be used' },
      { when: 'the resource is a Secret or ConfigMap', says: 'that those cannot be read' },
      { when: 'neither a deployment nor a cluster is named', says: 'to name one' },
    ],
    parameters: {
      type: 'object',
      properties: {
        verb: { type: 'string', enum: ['get', 'describe', 'top'], description: 'How to read it.' },
        resource: { type: 'string', description: 'What to read: pods, deployments, services, pvc, events, statefulsets, jobs; or nodes, pv, namespaces for a whole cluster.' },
        name: { type: 'string', description: 'One object by name. Leave out to list them all.' },
        deployment: { type: 'string', description: 'The deployment whose namespace to look in.' },
        cluster: { type: 'string', description: 'The cluster, for nodes, volumes and namespaces.' },
      },
      required: ['verb', 'resource'],
    },
  },
  {
    name: 'cluster_capacity',
    summary: 'Measure how busy a cluster\'s nodes are (CPU and memory in use), or how much one deployment\'s pods use',
    guidance: 'Use this when something might not fit or is being starved. Without a cluster or deployment it measures the management cluster.',
    binding: 'platform',
    effect: 'read',
    idempotent: true,
    openWorld: true,
    status: 'draft',
    returns: 'node usage and the node list, or the deployment\'s pod usage',
    failures: [NO_DEPLOYMENT, { when: 'the metrics server is not running', says: 'that no usage was reported' }],
    parameters: {
      type: 'object',
      properties: {
        cluster: { type: 'string', description: 'The cluster to measure.' },
        deployment: { type: 'string', description: 'Measure this deployment\'s pods instead.' },
      },
    },
  },
];
