export const ODOO_CHECK_SCRIPT = [
  "#!/bin/sh",
  "set -eu",
  "if [ $# -lt 1 ]; then",
  "  echo \"usage: odoo-check <module[,module]> [addons-dir]\" >&2",
  "  exit 2",
  "fi",
  "modules=\"$1\"",
  "addons=\"${2:-$PWD/addons}\"",
  "tags=$(printf '%s' \"$modules\" | tr ',' '\\n' | sed 's|^|/|' | paste -sd, -)",
  "pgbin=$(ls -d /usr/lib/postgresql/*/bin | sort -V | tail -1)",
  "state=$(mktemp -d /tmp/odoo-check.XXXXXX)",
  "log=\"$state/odoo.log\"",
  "cleanup() {",
  "  \"$pgbin/pg_ctl\" -D \"$state/pg\" -m fast stop >/dev/null 2>&1 || true",
  "  rm -rf \"$state\"",
  "}",
  "trap cleanup EXIT",
  "\"$pgbin/initdb\" -D \"$state/pg\" -U odoo --auth=trust --locale=C.UTF-8 --encoding=UTF8 >/dev/null",
  "\"$pgbin/pg_ctl\" -D \"$state/pg\" -o \"-k $state -c listen_addresses=''\" -l \"$state/pg.log\" -w start >/dev/null",
  "status=0",
  "odoo --db_host=\"$state\" --db_user=odoo --data-dir=\"$state/data\" \\",
  "  --addons-path=\"/usr/lib/python3/dist-packages/odoo/addons,$addons\" \\",
  "  -d check -i \"$modules\" --test-enable --test-tags \"$tags\" --stop-after-init --log-level=test --without-demo=all >\"$log\" 2>&1 || status=$?",
  "grep -E \"odoo\\.tests\\.(result|stats)|odoo\\.modules\\.loading: (Modules loaded|loading)|( ERROR | CRITICAL )|FAIL\" \"$log\" | tail -40",
  "if [ \"$status\" -ne 0 ] || grep -qE \" (ERROR|CRITICAL) \" \"$log\"; then",
  "  echo \"odoo-check: FAILED \u2014 $modules did not install cleanly, or a test failed (exit $status)\"",
  "  exit 1",
  "fi",
  "echo \"odoo-check: PASSED \u2014 $modules installed and its tests pass\"",
].join('\n') + '\n';
