export const ODOO_E2E_SCRIPT = [
  "#!/bin/sh",
  "set -eu",
  "if [ $# -lt 2 ]; then",
  "  echo \"usage: odoo-e2e <module[,module]> <spec-or-dir> [more specs] (run from the repository root; addons in ./addons)\" >&2",
  "  exit 2",
  "fi",
  "modules=\"$1\"",
  "shift",
  "addons=\"${ODOO_ADDONS:-$PWD/addons}\"",
  "pgbin=$(ls -d /usr/lib/postgresql/*/bin | sort -V | tail -1)",
  "state=$(mktemp -d /tmp/odoo-e2e.XXXXXX)",
  "odoo_pid=\"\"",
  "cleanup() {",
  "  [ -n \"$odoo_pid\" ] && kill \"$odoo_pid\" 2>/dev/null || true",
  "  \"$pgbin/pg_ctl\" -D \"$state/pg\" -m fast stop >/dev/null 2>&1 || true",
  "  rm -rf \"$state\"",
  "}",
  "trap cleanup EXIT",
  "\"$pgbin/initdb\" -D \"$state/pg\" -U odoo --auth=trust --locale=C.UTF-8 --encoding=UTF8 >/dev/null",
  "\"$pgbin/pg_ctl\" -D \"$state/pg\" -o \"-k $state -c listen_addresses=''\" -l \"$state/pg.log\" -w start >/dev/null",
  "common=\"--db_host=$state --db_user=odoo --data-dir=$state/data --addons-path=/usr/lib/python3/dist-packages/odoo/addons,$addons -d e2e\"",
  "if ! odoo $common -i \"$modules\" --without-demo=all --stop-after-init >\"$state/install.log\" 2>&1; then",
  "  tail -20 \"$state/install.log\"",
  "  echo \"odoo-e2e: FAILED \u2014 $modules did not install\"",
  "  exit 1",
  "fi",
  "port=${ODOO_E2E_PORT:-8069}",
  "odoo $common --http-port=\"$port\" --db-filter='^e2e$' --no-database-list --workers=0 >\"$state/odoo.log\" 2>&1 &",
  "odoo_pid=$!",
  "for i in $(seq 1 60); do",
  "  if curl -fsS \"http://127.0.0.1:$port/web/health\" >/dev/null 2>&1; then break; fi",
  "  sleep 1",
  "done",
  "curl -fsS \"http://127.0.0.1:$port/web/health\" >/dev/null || { tail -20 \"$state/odoo.log\"; echo \"odoo-e2e: FAILED \u2014 Odoo did not start\"; exit 1; }",
  "mkdir -p \"$PWD/e2e-results\"",
  "status=0",
  "BASE_URL=\"http://127.0.0.1:$port\" ODOO_LOGIN=admin ODOO_PASSWORD=admin PLAYWRIGHT_JSON_OUTPUT_NAME=\"$PWD/e2e-results/report.json\" \\",
  "  playwright test \"$@\" --reporter=line,json --output=\"$PWD/e2e-results/artifacts\" > \"$state/e2e.out\" 2>&1 || status=$?",
  "tail -30 \"$state/e2e.out\"",
  "if [ \"$status\" -ne 0 ]; then echo \"odoo-e2e: FAILED \u2014 the browser tests did not pass (exit $status)\"; exit 1; fi",
  "echo \"odoo-e2e: PASSED \u2014 $modules installed and the browser tests pass\"",
].join('\n') + '\n';

export const KOALA_E2E_SCRIPT = [
  "#!/bin/sh",
  "set -eu",
  "modules=$(for manifest in addons/*/__manifest__.py; do [ -f \"$manifest\" ] && basename \"$(dirname \"$manifest\")\"; done | paste -sd, -)",
  "if [ -z \"$modules\" ]; then",
  "  echo \"koala-e2e: FAILED \u2014 there is no module under addons/ to serve\"",
  "  exit 1",
  "fi",
  "[ $# -gt 0 ] || set -- e2e",
  "exec odoo-e2e \"$modules\" \"$@\"",
].join('\n') + '\n';
