import { spawn, type ChildProcess } from 'child_process';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../../../../');
const BIN_DIR = path.join(PROJECT_ROOT, 'bin');
const KUBECTL = path.join(BIN_DIR, 'kubectl');

interface PortForwardEntry {
  process: ChildProcess;
  localPort: number;
  ready: Promise<number>;
}

interface ServiceTarget {
  service: string;
  namespace: string;
  remotePort: number;
  /** Override the kubectl port-forward target resource (e.g. "deployment/traefik"). Defaults to "svc/{service}". */
  resource?: string;
  /** Path appended to the port-forward URL (e.g. "/dashboard/" for Traefik). Defaults to "/". */
  dashboardPath?: string;
}

const SERVICE_TARGETS: Record<string, ServiceTarget> = {
  prometheus: {
    service: 'kube-prometheus-stack-prometheus',
    namespace: 'monitoring',
    remotePort: 9090,
  },
  grafana: {
    service: 'kube-prometheus-stack-grafana',
    namespace: 'monitoring',
    remotePort: 80,
  },
  traefik: {
    service: 'traefik',
    // Not kube-system — this platform's own Traefik (constructs/ingress.ts) deploys into its
    // own 'traefik' namespace, and k3s's bundled Traefik (which *would* be in kube-system) is
    // explicitly disabled at cluster-create time (scripts/cluster.sh --disable=traefik).
    // Confirmed live.
    namespace: 'traefik',
    // Not 9000 — confirmed live via the pod's own containerPort list that this chart's
    // dashboard/API entrypoint (named "traefik") is actually 8080. The port-forward target
    // was pointed at a port nothing in the container listens on at all.
    remotePort: 8080,
    resource: 'deployment/traefik',
    dashboardPath: '/dashboard/',
  },
  gitea: {
    service: 'gitea-http',
    namespace: 'gitea',
    remotePort: 3000,
  },
  alertmanager: {
    // Ships as a subchart of kube-prometheus-stack (same as Grafana above), not its own
    // release. Confirmed live via `kubectl get svc -n monitoring` — the Service is named after
    // the chart release ("kube-prometheus-stack-alertmanager"), NOT the pod name pattern
    // ("alertmanager-kube-prometheus-stack-alertmanager-0", generated by the Alertmanager
    // StatefulSet/CR) — easy to guess wrong from the pod name alone.
    service: 'kube-prometheus-stack-alertmanager',
    namespace: 'monitoring',
    remotePort: 9093,
  },
};

export class ClusterProxyService {
  private forwards: Map<string, Map<string, PortForwardEntry>> = new Map();

  private key(clusterId: string, serviceKey: string) {
    return `${clusterId}::${serviceKey}`;
  }

  async ensurePortForward(
    clusterId: string,
    serviceKey: string,
    kubeconfigPath: string,
  ): Promise<string> {
    const target = SERVICE_TARGETS[serviceKey];
    if (!target) throw new Error(`Unknown service: ${serviceKey}`);

    const clusterForwards = this.forwards.get(clusterId) ?? new Map();
    this.forwards.set(clusterId, clusterForwards);

    const existing = clusterForwards.get(serviceKey);
    if (existing) {
      const port = await existing.ready;
      return `http://localhost:${port}${target.dashboardPath ?? '/'}`;
    }

    const localPort = 0; // let the OS pick a free port

    const child = spawn(
      KUBECTL,
      [
        'port-forward',
        '--address', '127.0.0.1',
        '--kubeconfig', kubeconfigPath,
        '-n', target.namespace,
        target.resource ?? ('svc/' + target.service),
        `${localPort}:${target.remotePort}`,
      ],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    );

    let resolvePort: (port: number) => void;
    let rejectPort: (err: Error) => void;
    const ready = new Promise<number>((resolve, reject) => {
      resolvePort = resolve;
      rejectPort = reject;
    });

    let stderrBuf = '';
    let resolved = false;

    child.stderr?.on('data', (data: Buffer) => {
      stderrBuf += data.toString();
    });

    child.stdout?.on('data', (data: Buffer) => {
      const text = data.toString();
      // kubectl prints: "Forwarding from 127.0.0.1:54321 -> 3000"
      const match = text.match(/Forwarding from 127\.0\.0\.1:(\d+)/);
      if (match && !resolved) {
        resolved = true;
        resolvePort(parseInt(match[1] ?? '0', 10));
      }
    });

    child.on('error', (err) => {
      if (!resolved) {
        resolved = true;
        rejectPort(err);
      }
    });

    child.on('close', (code) => {
      clusterForwards.delete(serviceKey);
      if (!resolved) {
        resolved = true;
        const detail = stderrBuf.trim() || 'no stderr';
        rejectPort(new Error(`port-forward exited with code ${code}: ${detail}`));
      }
    });

    const entry: PortForwardEntry = { process: child, localPort: 0, ready };
    clusterForwards.set(serviceKey, entry);

    const port = await ready;
    entry.localPort = port;
    return `http://localhost:${port}${target.dashboardPath ?? '/'}`;
  }

  /**
   * Logs in as the given service's own real admin account, server-side, and returns the raw
   * Set-Cookie header value(s) from that login response to relay onto our own response — the
   * browser ends up with a genuine, real session (the exact same one it would get by typing the
   * password itself), without the password ever being sent to or displayed in the browser.
   * Not a trust-bypass/shared-secret mechanism (like an auth-proxy trusted header would be) —
   * this is the service's own normal login flow, just automated. Both flows confirmed live
   * against real Grafana/Gitea instances (no CSRF token required by either as configured here).
   *
   * `targetUrl` must be the exact URL the browser will be redirected to afterward (i.e.
   * ensurePortForward's return value) — cookies are host-scoped (not port-scoped, per RFC 6265),
   * so this only works because ensurePortForward returns a "localhost" URL matching the hostname
   * this backend itself is reached on, not "127.0.0.1" (a different string, and browsers treat
   * cookie hosts as an exact string match, not an IP-resolution match).
   */
  async getAutoLoginCookies(
    serviceKey: string,
    targetUrl: string,
    credentials: { username: string; password: string },
  ): Promise<string[]> {
    if (serviceKey === 'grafana') {
      const res = await fetch(`${targetUrl}login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user: credentials.username, password: credentials.password }),
      });
      if (!res.ok) throw new Error(`Grafana login failed: HTTP ${res.status}`);
      return res.headers.getSetCookie();
    }

    if (serviceKey === 'gitea') {
      // Two-step: an initial GET establishes a pre-auth session cookie Gitea's login POST
      // expects to see carried back — without it the POST silently re-renders the login form
      // (200, not an error) instead of authenticating. Confirmed live.
      const initial = await fetch(`${targetUrl}user/login`);
      const preAuthCookie = initial.headers.getSetCookie().map((c) => c.split(';')[0]).join('; ');
      const res = await fetch(`${targetUrl}user/login`, {
        method: 'POST',
        redirect: 'manual', // a successful login 303-redirects — don't follow it, just read its Set-Cookie
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          Cookie: preAuthCookie,
        },
        body: new URLSearchParams({ user_name: credentials.username, password: credentials.password }).toString(),
      });
      if (res.status !== 303) throw new Error(`Gitea login failed: HTTP ${res.status}`);
      return res.headers.getSetCookie();
    }

    return [];
  }

  stopForCluster(clusterId: string) {
    const clusterForwards = this.forwards.get(clusterId);
    if (!clusterForwards) return;
    for (const [serviceKey, entry] of clusterForwards) {
      entry.process.kill();
      clusterForwards.delete(serviceKey);
    }
    this.forwards.delete(clusterId);
  }

  stopAll() {
    for (const [clusterId] of this.forwards) {
      this.stopForCluster(clusterId);
    }
  }
}
